version: '3.8'

services:
  reservation-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: reservation-api-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - INVENTORY_GRPC_ADDRESS=${INVENTORY_GRPC_ADDRESS}
      - JWT_ISSUER_URI=${JWT_ISSUER_URI}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - LOGGING_LEVEL_ROOT=INFO
      - MANAGEMENT_METRICS_EXPORT_OTLP_ENABLED=true
    volumes:
      - ./logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traffic-tacos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traffic-tacos:
    driver: bridge
