# Local Development Configuration
spring:
  application:
    name: reservation-api
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/traffic-tacos

# WebFlux Configuration
webflux:
  base-path: /v1

# Jackson Configuration (Performance Optimization)
jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false

# AWS Configuration for LocalStack
aws:
  region: ap-northeast-2
  dynamodb:
    endpoint: http://localhost:8000
  eventbridge:
    endpoint: http://localhost:4566

# DynamoDB Tables
app:
  dynamodb:
    tables:
      reservations: reservations
      orders: orders
      idempotency: idempotency
      outbox: outbox
  reservation:
    hold-duration-seconds: 60
    idempotency-ttl-seconds: 300
    max-retries: 3

# gRPC Configuration
grpc:
  client:
    inventory:
      address: localhost:9090
      negotiation-type: plaintext

# Logging Configuration
logging:
  level:
    com.traffictacos.reservation: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8080

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /v1/**
