apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-api
  labels:
    app: reservation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-api
  template:
    metadata:
      labels:
        app: reservation-api
    spec:
      containers:
        - name: reservation-api
          image: 137406935518.dkr.ecr.ap-southeast-2.amazonaws.com/traffic-tacos/reservation-api:latest
          ports:
            - containerPort: 8010 # REST
            - containerPort: 8011 # gRPC
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8010
            initialDelaySeconds: 30
            periodSeconds: 20
