apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-api
  labels:
    app: reservation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-api
  template:
    metadata:
      labels:
        app: reservation-api
    spec:
      containers:
        - name: reservation-api
          image: 137406935518.dkr.ecr.ap-southeast-2.amazonaws.com/traffic-tacos/reservation-api:latest
          ports:
            - name: http
              containerPort: 8010 # REST
            - name: grpc
              containerPort: 8011 # gRPC
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: grpc
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
